name: Deploy netspeedtest to EC2

on:
  push:
    branches:
      - deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy docker-compose file with scp
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source: 'docker-compose.yml'
          target: '/home/ec2-user/'

      - name: Copy scripts directory with scp
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source: 'scripts'
          target: '/home/ec2-user/'

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            export MONGO_URI=${{ secrets.MONGO_URI }}
            export CLIENT_IP=${{ secrets.CLIENT_IP }}
            export PULSE_CNT_SERVER=${{ secrets.PULSE_CNT_SERVER }}
            export GCP_PROJECT_ID=${{ secrets.GCP_PROJECT_ID }}
            export GCS_BUCKET=${{ secrets.GCS_BUCKET }}
            export GCP_SA_KEY=${{ secrets.GCP_SA_KEY }}
            export DATABASE_NAME=${{ secrets.DATABASE_NAME }}
            export BACKUP_FILE=${{ secrets.BACKUP_FILE }}
            cd /home/ec2-user
            docker-compose down
            docker-compose up -d
            # Install gsutil if not exists
            if ! command -v gsutil &> /dev/null
            then
                # Install gsutil
                curl https://sdk.cloud.google.com | bash
                source /root/google-cloud-sdk/path.bash.inc
            else
                # Update gcloud components
                gcloud components update
            fi
            # Auth with GCP
            echo $GCP_SA_KEY | base64 --decode > sa_key.json
            gcloud auth activate-service-account --key-file sa_key.json
            gcloud config set project $GCP_PROJECT_ID
            # Download backup file from GCS
            gsutil cp gs://$GCS_BUCKET/$BACKUP_FILE .
            # Copy backup file into MongoDB Docker container
            docker cp $BACKUP_FILE ec2-user-mongodb-1:/tmp/
            # Install mongodb-org-tools in the MongoDB Docker container if it does not exist
            docker exec ec2-user-mongodb-1 bash -c 'if ! command -v mongorestore &> /dev/null; then apt-get update && apt-get install -y mongodb-org-tools; fi'
            # Restore MongoDB from backup inside Docker container
            docker exec ec2-user-mongodb-1 mongorestore --uri $MONGO_URI --nsInclude "$DATABASE_NAME.*" --gzip --archive=/tmp/$BACKUP_FILE
